baseURL = 'https://example.org/'
title = 'HUGOpedia'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja'
    languageDirection = 'ltr'
    languageName = 'Japanese'
    weight = 2
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1



[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
[frontmatter]
lastmod = ["lastmod", ":git", "date"]

[taxonomies]
  category = "categories"
  tag = "tags"


[menus]
  [[menus.main]]
    name = 'Q and A'
    pageRef = '/qanda'
    weight = 10
  [[menus.main]]
    name = 'Contract'
    pageRef = '/contract'
    weight = 20
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1